title: "Your Name"
email: "your.email@example.com"
description: "Microbiome Researcher | Environmental Microbiomes | Bioinformatics"
url: "https://danibeta07.github.io" # the base hostname & protocol for your site
baseurl: ""

# Navigation
header_pages:
  - index.md
  - research.md
  - projects.md
  - publications.md
  - contact.md

# Custom Domain
remote_theme: alshedivat/al-folio
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Daniela Betancurt-Anzola"
  avatar: "/assets/img/profile.jpg"
